stages:
  - tf_plan
  - tf_apply
  
terraform plan dev:
  stage: tf_plan
  image: hashicorp/terraform:0.13.5
  only:
    refs:
      - fake_master
  script:
    - cd terraform/environment/dev
    - terraform init
  